import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

final chatsProvider = Provider<List<Map<String, dynamic>>>((ref) {
  return [
    {
      "name": "Saved Messages",
      "type": "All",
      "message": "IMG_420.png",
      "time": "Fri",
      "unread": 0,
      "color": Colors.blue,
      "read": true,
      "muted": false,
      "pinned": true,
    },
    {
      "name": "Emma Torreaux",
      "type": "Work",
      "message": "Bob says hi.",
      "time": "9:41",
      "unread": 0,
      "color": Colors.orange,
      "read": true,
      "muted": false,
      "pinned": false,
    },
    {
      "name": "Roberto",
      "type": "Work",
      "message": "Say hello to Emma.",
      "time": "9:41",
      "unread": 1,
      "color": Colors.green,
      "read": false,
      "muted": false,
      "pinned": false,
    },
    {
      "name": "8Bit Times",
      "type": "Groups",
      "message": "8Bit Times started a Live Stream",
      "time": "9:41",
      "unread": 4,
      "color": Colors.red,
      "read": false,
      "muted": true,
      "pinned": false,
    },
    {
      "name": "Digital Nomads",
      "type": "Groups",
      "message": "Jennie: We just reached 2,500 members",
      "time": "9:22",
      "unread": 12,
      "color": Colors.teal,
      "read": false,
      "muted": true,
      "pinned": true,
    },
    {
      "name": "Penelope",
      "type": "Unread",
      "message": "See you tomorrow 👋",
      "time": "9:12",
      "unread": 102,
      "color": Colors.purple,
      "read": true,
      "muted": false,
      "pinned": false,
    },
    {
      "name": "ChatGPT Bots",
      "type": "Bots",
      "message": "See you tomorrow 👋",
      "time": "9:12",
      "unread": 0,
      "color": Colors.purple,
      "read": true,
      "muted": false,
      "pinned": false,
    },
    // ...rest of your chats
  ];
});
